"""Affine map between MuJoCo (policy) and URDF (ROS) joint conventions.

joint_map.yaml is generated by tools/fit_joint_map.py:
    q_urdf = sign * q_mujoco + offset
Signs are +/-1, so the inverse is q_mujoco = sign * (q_urdf - offset).
"""

import numpy as np
import yaml


class JointMap:
    def __init__(self, yaml_path):
        raw = yaml.safe_load(open(yaml_path))["joint_map"]
        self._sign = {n: float(v["sign"]) for n, v in raw.items()}
        self._offset = {n: float(v["offset"]) for n, v in raw.items()}

    def names(self):
        return list(self._sign)

    def sign(self, names):
        return np.array([self._sign[n] for n in names])

    def offset(self, names):
        return np.array([self._offset[n] for n in names])

    def to_urdf(self, names, q_mjc):
        return self.sign(names) * np.asarray(q_mjc) + self.offset(names)

    def to_mjc(self, names, q_urdf):
        return self.sign(names) * (np.asarray(q_urdf) - self.offset(names))

    def vel_to_urdf(self, names, dq_mjc):
        return self.sign(names) * np.asarray(dq_mjc)

    def vel_to_mjc(self, names, dq_urdf):
        return self.sign(names) * np.asarray(dq_urdf)
